name: dockerfile upload

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'

jobs:
  docker-image-upload:
    name: upload docker image to ecr
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front-end/

    environment:
      name: production   

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
          
    - name: "authenticate docker client"
      run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 826589250962.dkr.ecr.eu-central-1.amazonaws.com       

    - name: "create&push docker image"
      run: |
        docker build -t todo-app:1.0 .
        docker tag todo-app:1.0 826589250962.dkr.ecr.eu-central-1.amazonaws.com/todo-app:1.0
        docker push 826589250962.dkr.ecr.eu-central-1.amazonaws.com/todo-app:1.0
